### PR TITLE
Version bump for gulp-svg2ttf dependency to fix icon issues in IE

### PR DESCRIPTION
**Pull request by RobeeeJay**
Should only be merged after https://github.com/nfroidure/gulp-svg2ttf/pull/7

### CODE REVIEW

**Comment by marcofranssen** [comment]
What is the timespan we can have this pull request being accepted? We are suffering some issues with IE11 at the moment. Would be cool to have this version being released soon.

**Comment by nfroidure** [comment]
@marcofranssen the timespan is, asap as soon as tests are passing. First here https://github.com/nfroidure/gulp-svg2ttf/pull/7 than in this PR.

Feel free to do it, won't be long imo.

**Comment by RobeeeJay** [comment]
This should now pass tests if re-run!

**Comment by nfroidure** [comment]
Let's go! https://travis-ci.org/nfroidure/gulp-iconfont/builds/114551790

**Comment by RobeeeJay** [comment]
Ok will investigate, probably for the same reason the other repo was breaking, thanks for clicking the rebuild!

I shall return... :)

**Comment by RobeeeJay** [comment]
I have returned. :) With fixed font test files (again from a binary diff they just contain the changes to HHEAD).

**Pull request merged**
