### PR TITLE
Add support for Node.js 11/12

### PR DESCRIPTION
**Pull request by pioug**
So far we updated: 
- https://github.com/nfroidure/ttf2woff2/releases/tag/v3.0.0
- https://github.com/nfroidure/gulp-ttf2woff2/releases/tag/v3.0.0

We're almost done 😅

### CODE REVIEW

**Comment by pioug** [comment]
Thanks you @NaridaL for reviewing! Do you think we can release a (major) update for `gulp-icon-font` now? 

Same with the other packages, I'll be happy to help with all the chores 🙌 (bump, triage issues/PR, small updates...)

**Comment by NaridaL** [comment]
@pioug Does this need a major version? Is there anything other than the fact that gulp-ttf2woff2 no longer supports node 0.12? The `package.json` here says `"node": ">= 6.11.1"` anyway.

**Comment by pioug** [comment]
Good point! We are dropping very old Node versions. I think we can bump a minor version since it doesn't affect the compatibility for this package 👍

**Comment by pioug** [comment]
Thank you @nfroidure for inviting me to the repository! I bumped and tagged a new version https://github.com/nfroidure/gulp-iconfont/releases/tag/v10.0.3. Next is publishing on npm and I think we're good with Node 12 💦 

Thanks for following up on my PRs 🙌

**Comment by NaridaL** [comment]
👍 Yeah, sorry I was waiting on feedback to https://github.com/nfroidure/gulp-svgicons2svgfont/issues/40, which would also need changes here, but this works too :-D 

I can publish to npm this evening unless @nfroidure gives you access there too.

**Comment by nfroidure** [comment]
Jut added you @pioug thank you both for taking time to update all that legacy :)

**Pull request merged**
