### PR TITLE
TTFAutohint custom path and test case

### PR DESCRIPTION
**Pull request by sabberworm**
This is a version of #128 that includes a test for hinting. Since the `ttfautohint` binary is compiled in travis, this makes the travis build much longer.

Also, because ttfautohint adds some kind of timestamp to the generated file, which can’t be removed, this test is rather hacky, zeroing out the affected bytes (I hope I got them all).

To test locally, a Dockerfile is provided as well as a wrapper script that calls either the native or the dockerized version of `ttfautohint`.

To build the `ttfautohint` docker image (for local testing), do:

    docker build -t ttfautohint:1.5 tests/ttfautohint

Feel free to choose between this version and the one from #128.

### CODE REVIEW

**Comment by sabberworm** [comment]
@nfroidure Now that I can merge this myself, do you want me to decide if we want this version or #128?

**Comment by nfroidure** [comment]
@sabberworm i won't have the time to look at it after a while so if you are confident with your changes, just merge it. i'll give you NPM publication access, what is your npm nickname?

**Comment by sabberworm** [comment]
My npm user is [sabberworm](https://www.npmjs.com/~sabberworm), too.

**Comment by nfroidure** [comment]
Done, let's decrease the bus factor ;).

**Comment by sabberworm** [comment]
@nfroidure So I’ve merged. What is your versioning scheme? Should I do 8.0.1?

**Comment by nfroidure** [comment]
I semver all the things so it depends the changes you made ;) http://semver.org

**Comment by nfroidure** [comment]
Also, you're probably aware of it but i always use npm version patch/minor/major to stay consistent for each versions.

**Comment by nfroidure** [comment]
Btw, you contributions are very welcome and thank you for the great work you did.

**Pull request merged**
